### ISSUE TITLE
关于你方 CodeEncryption 软件侵犯我方软件著作权的声明

### ISSUE THREAD

**Issue by swoole-tech** [JaderH/GreenBox#2]
Jader (Github)：

我是上海识沃科技的法律代表，就您公司所制作、发布或销售的软件 CodeEncryption (https://github.com/Jader/CodeEncryption) 存在的侵权问题，向您发出此正式函件。

我们得悉，您的软件涉嫌侵犯了我们的知识产权、著作权以及其他相关权益，以下是我们发现的侵权行为：

根据相关法律法规，我方要求您立即停止侵权行为，并采取以下措施：

停止制作、发布、销售、复制、分发以及软件相关服务的一切活动，确保不再侵犯我们的知识产权；
删除涉及侵权的软件及其相关文件、文档、链接等，确保不再存在任何侵权内容；
请您向我方提供关于软件销售情况的详细报告，包括但不限于销售数量、销售渠道、销售收入等，以便我方评估损失并采取进一步的法律行动；
在收到本函后的48小时内回复，确认您已经采取了上述措施。
我们理解并重视知识产权保护的重要性，同时欢迎您提供有效证据证明您的软件不构成侵权行为。如果您有合理解释或者无法履行上述要求的情况，请在收到本函后的48小时内提供书面答复，陈述您的观点并提供相关证据。

请您务必认真对待此函件，因不履行上述要求可能会导致严重法律后果。我方已收集、固定了相关证据，并将继续监测您的软件行为，并在必要时采取法律行动以保护我们的权益。

上海识沃网络科技有限公司
2023/10/26

**Comment by Jader** [comment]
关于你反馈的情况是不存在的，该工具只是环境配置，仅供学习参考
